### ISSUE TITLE
Update to latest Stack

### ISSUE THREAD

**Issue by StarpTech** [hemerajs/aither#6]
Update Hemera to 3, Use Jaeger instead Zipkin, Use Hapi 17

**Comment by BransonGitomeh** [comment]
also maybe use this nats? https://github.com/nats-io/nats-docker

**Comment by StarpTech** [comment]
Hi @BransonGitomeh thanks for checking out Aither. Great idea, could you create a PR?

**Comment by BransonGitomeh** [comment]
hey, no icant manage to make a PR since im still learning, ive definately taken the project apart multiple times and put it back together. i now think the nats docker instance you set up is ok and im working with it as is , great work man

**Comment by BransonGitomeh** [comment]
in regards to using hapi 17, im having issues with the zipkin instrumentation , it doesnt support 17 yet, [#185](https://github.com/openzipkin/zipkin-js/issues/185)

**Comment by StarpTech** [comment]
Hi, I updated aither to the latest stack. @BransonGitomeh I'm using jaeger instead zipkin
